parameters:
  versionSuffix: ''
  configuration: 'Release'

jobs:
- job:
  pool:
    vmImage: 'windows-2019'
  
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet'
    inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: config
        nugetConfigPath: NuGet.config

  - task: DotNetCoreCLI@2
    displayName: 'Build and Pack'
    inputs:
        command: custom
        custom: pack
        packagesToPack: '**/*.csproj'
        arguments: '--configuration ${{ parameters.configuration }} ${{ parameters.versionSuffix }}'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '--configuration ${{ parameters.configuration }} --collect "Code coverage"'
      projects: '**/*.Tests.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'NuGet push'
    inputs:
        command: push
        publishVstsFeed: 'wlsoft'
        packagesToPush: '**/*.nupkg'