name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Publish the package to NuGet
      run: dotnet nuget push GraphApi.Facebook.Client/bin/Release/*.nupkg
